### PR TITLE
Added Windows TLS test

### PR DESCRIPTION
**Pull request by adrianherrera**
Hey guys,

I'm starting to have a look at implementing TLS support for Windows PE files. If this is something that you're interested in, I've prepared this test program and compiled it with VC to generate a binary.

Regards,
Adrian

### CODE REVIEW

**Comment by ltfish** [comment]
Thank you, we definitely want to add this support!

For test cases, can you please rename the directories to `{tests,tests_src}/arch/platform/filename`, like `tests/x86/windows/main.c`? We want to make things more organized, and we will reorganize other test cases later.

**Comment by adrianherrera** [comment]
Hey Fish,

I restructured the directories as required. Please let me know if there are any other issues. Hopefully within the next few days they'll be a PR to CLE with Windows TLS support.

Regards,
Adrian

**Comment by rhelmot** [comment]
what fish described was not correct, I don't think there should be an x86 folder under `tests_src`. Source code is platform-independant, and shouldn't require an architecture specifier, right?

**Comment by adrianherrera** [comment]
Sure. What about binaries? Seeing as I have 2 different angr members telling me different things, why don't you guys decide and let me know. I can then make the appropriate changes to the PR.

**Comment by ltfish** [comment]
Hi Adrian,

I was wrong in my previous comment. After discussing with other angr team members, now I believe we should put all source code together, and only split binaries by platforms. Sorry for any confusion that I have caused.

I can update your PR for you if you want!

**Comment by adrianherrera** [comment]
No no, it's all fine! I've moved the source out of an architecture-specific directory. If you need to make any further changes, please go ahead and update the PR as required.

Thanks guys!

**Comment by ltfish** [comment]
Sorry, it takes me a few days to get to this PR. It's so hard to find time to work while traveling :-(

Thank you!

**Comment by adrianherrera** [comment]
All good, enjoy your travels!

**Pull request merged**
