### PR TITLE
four new archs binary samples added

### PR DESCRIPTION
**Pull request by pwnslinger**
These test cases will be applied in my latest modification to fuzzer_test in which completely tests all supported archs so far. 

archs:
`alpha, hppa, s390x, sh4`

### CODE REVIEW

**Comment by notxvilka** [comment]
@pwnslinger @ltfish could you please elaborate under what license these tests are distributed? We want to use them in the [Rizin testuite](https://github.com/rizinorg/rizin-testbins/)

**Comment by rhelmot** [comment]
This looks to be code contributed under BSD-2 but statically linked against glibc. Not sure how that affects things.

**Comment by rhelmot** [comment]
yeah, all original code is MIT per LICENSE.md but glibc is LGPL per LICENSE.libc

**Comment by notxvilka** [comment]
> yeah, all original code is MIT per LICENSE.md but glibc is LGPL per LICENSE.libc

Thank you, both are suitable for us.

**Pull request merged**
